'use strict';

const { supabase } = require('./supabase');
const { buildMachineQrValue } = require('../utils/qr');
const { getGymConfig } = require('../../config/gym-config');
const ApiError = require('../utils/ApiError');

async function gymBaseUrl(gymId) {
  const { data } = await supabase.from('gyms').select('feature_flags').eq('id', gymId).single();
  const cfg = getGymConfig(gymId, data && data.feature_flags);
  return cfg.base_app_url; // undefined unless a gym overrides it
}

/** Public: active machines for a gym. */
async function listActive(gymId) {
  const { data, error } = await supabase
    .from('machines').select('*').eq('gym_id', gymId).eq('is_active', true).order('name');
  if (error) throw error;
  return data;
}

/** Public: fetch a machine by its QR code id (usage instructions screen). */
async function getByQrCode(gymId, qrCodeId) {
  const { data, error } = await supabase
    .from('machines').select('*').eq('gym_id', gymId).eq('qr_code_id', qrCodeId).limit(1);
  if (error) throw error;
  if (!data || !data[0]) throw ApiError.notFound('Machine not found', 'MACHINE_NOT_FOUND');
  return data[0];
}

async function getById(gymId, id) {
  const { data, error } = await supabase
    .from('machines').select('*').eq('gym_id', gymId).eq('id', id).limit(1);
  if (error) throw error;
  if (!data || !data[0]) throw ApiError.notFound('Machine not found', 'MACHINE_NOT_FOUND');
  return data[0];
}

/** Admin: register a machine. qr_code_id is generated by the DB default. */
async function create(gymId, body) {
  const { data, error } = await supabase
    .from('machines')
    .insert({
      gym_id: gymId,
      name: body.name,
      type: body.type,
      zone: body.zone,
      instructions: body.instructions || [],
      is_active: body.is_active ?? true,
    })
    .select('*').single();
  if (error) throw error;
  return data;
}

async function update(gymId, id, patch) {
  const allowed = {};
  for (const k of ['name', 'type', 'zone', 'instructions', 'is_active']) {
    if (patch[k] !== undefined) allowed[k] = patch[k];
  }
  const { data, error } = await supabase
    .from('machines').update(allowed).eq('gym_id', gymId).eq('id', id).select('*').single();
  if (error) {
    if (error.code === 'PGRST116') throw ApiError.notFound('Machine not found', 'MACHINE_NOT_FOUND');
    throw error;
  }
  return data;
}

/** Admin: QR value (deep-link string) for printing. */
async function getQrValue(gymId, id) {
  const machine = await getById(gymId, id);
  const base = await gymBaseUrl(gymId);
  return {
    machine_id: machine.id,
    qr_code_id: machine.qr_code_id,
    qr_value: buildMachineQrValue(machine.qr_code_id, base),
  };
}

module.exports = { listActive, getByQrCode, getById, create, update, getQrValue };
